version: '3.7'

services:

  mongo_alfa3bd:
    image: mongo
    container_name: mongo-production
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - ${PWD}/_data/mongo:/data/db
      - ${PWD}/docker/_mongo/fixtures:/import
      - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 27017:27017

  backend_alfa3bd:
    build: ./alfa3bd_backend
    restart: always
    command: > 
        sh -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: 
      - ./.env
    depends_on: 
      - mongo_alfa3bd
  
  frontend_alfa3bd:
    build: ./alfa3bd_frontend
    restart: always
    # command: nginx -g daemon off
    ports:
      - 8080:80
      
